version: 2
updates:
#  - package-ecosystem: "npm"
#    directory: "ch9_release/src/Tailwind.Traders.Web/ClientApp"
#    schedule:
#      interval: "daily"
#    open-pull-requests-limit: 50
    
#  - package-ecosystem: "npm"
#    directory: "ch8_packages/npm"
#    schedule:
#      interval: "daily"
#    open-pull-requests-limit: 5
      
#  - package-ecosystem: "nuget"
#    directory: "ch9_release/src/Tailwind.Traders.Web"
#    schedule:
#      interval: "daily"
#    open-pull-requests-limit: 15

  - package-ecosystem: "docker"
    directory: "ch9_release/src/Tailwind.Traders.Web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
