name: Deploy-Azure

on: [workflow_dispatch]

env:
  appName: xyz-demo-shop

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.0.x'

    - name: Setup Node
      uses: actions/setup-node@v2.5.1
      with:
        node-version: 10.16.3    

    - name: Install dependencies in client app
      working-directory: ch9_release/src/Tailwind.Traders.Web/ClientApp
      run: npm install

    - name: Build and publish with dotnet
      working-directory: ch9_release/src/Tailwind.Traders.Web
      run: |
        dotnet build --configuration Release
        dotnet publish -c Release -o publish
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: website
        path: ch9_release/src/Tailwind.Traders.Web/publish
   
  Deploy:
    runs-on: ubuntu-latest
    environment: prod
    needs: Build
    
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v3
      
    - uses: actions/download-artifact@v2
      with:
        name: website
        path: website
    
    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.appName }}
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: website

    - name: Run a smoke test
      run: |
        url=https://${{ env.appName }}.azurewebsites.net/
        status=`curl --silent --head $url | head -1 | cut -f 2 -d' '`
        if [ "$status" != "200" ]
        then
            echo "Wrong HTTP Status. Expected: '200' - Actual: '$status'"
            exit 1
        fi
